- name: ensuring directories for {{ name }}
  file: path={{ item }} state=directory owner={{ user }}
  with_items: "{{ app_dirs }}"

- name: installing config for {{ name }}
  template: src=app.ini.j2 dest={{ supervisor_config_dir }}/{{ name }}.ini
  register: app_conf

# this resolves the "process group already active" issue when dealing 
# with a single process
- set_fact:
    group_name: "{{ name }}:"
  when: numprocs > 1
- set_fact:
    group_name: "{{ name }}"
  when: numprocs == 1

- name: starting {{ name }}
  supervisorctl: >
    state=present
    name="{{ group_name }}"
    supervisorctl_path={{ supervisorctl_path }}
    config={{ supervisor_config }}
  register: app_started

- name: reloading configuration for {{ name }}
  when: app_conf|changed and not app_started|changed
  shell: >
    {{ supervisorctl_path }} -c {{ supervisor_config }} reread;
    {{ supervisorctl_path }} -c {{ supervisor_config }} update {{ name }}
