- name: ensuring directories for {{ name }}
  file: path={{ item }} state=directory
  with_items: app_dirs

- name: installing config for {{ name }}
  template: src=app.ini.j2 dest={{ supervisor_config_dir }}/{{ name }}.ini
  register: app_conf

- name: starting {{ name }}
  supervisorctl: >
    state=present
    name="{{ name }}:"
    supervisorctl_path={{ supervisorctl_path }}
    config={{ supervisor_config }}
  register: app_started

- name: reloading configuration for {{ name }}
  when: app_conf|changed and not app_started|changed
  shell: >
    {{ supervisorctl_path }} -c {{ supervisor_config }} reread;
    {{ supervisorctl_path }} -c {{ supervisor_config }} update {{ name }}
